language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: unpredictable
  api_key:
    secure: ihwgdLM6k8XQv832GQn6hjUqTYrbzP3AKdCY0rRl7/0DNgMo4tZk+W4yxAwvSDfrKblpKtQAG3B2p8zCh04VNeEePLol5gkPRwBQ8uYX9fcS0AlKAvBWQNOz9R73xWKieIOm3RJjboNCeVOVLAiRNHJ6eEvd0ygZ5JqavXFCio3X3tB0mXFCX4bHmrYySOACIBxlVZ4FopPWPTfFnxZdTlc1PfcMkzwX5ODHv8AXkTd0eZL5Pbk+wtBIxrD6+IhQZ4DoQGHquaNGpXU4KonXc6NIUrB0H5mYeNALOtLOw4pfwcx3ncLSJ5lJcwFpb8xzhgzXOXAPaTmzke29qL8nQ0d8dxBmLYBnzRba3GMnEfuu4noVIZfmwu6qDWcepgFmndiZ57Ayq+AMmyMdXckvHKDL7XzLuEEGrojeagefS8BVV8BF53W/Reypo/h+TGGV4CojdhUaM+RbfGmqf+KFDhduZTxZ2JIcR96cCOmWa2Q6VSfl6ALQ1VXJO5loLKN3gZ+NQZj77oVt6rqZxBNUZ+hbfXKwZ6lJyKcBsX2B30TzWoQtAMLAejsfxA0ruJs6tRD4x8/EujqGUfb62CGs69c04Qi3YrkmfGCNv94NTA/yiGo1LzZU6SgL5rac8YGLFz6qxkFTAmTOBZogRT4NXYZEJh90TV7EWwErwyS1v/A=
